// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc_PewOq8vJps7Uo2YhWnpRldg62JVs7U',
    appId: '1:716695237276:web:754b063f39e7ac75523359',
    messagingSenderId: '716695237276',
    projectId: 'fruit-hub-954fa',
    authDomain: 'fruit-hub-954fa.firebaseapp.com',
    storageBucket: 'fruit-hub-954fa.appspot.com',
    measurementId: 'G-S32VVXZ3NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzJDCrOtyiz8en9eD6-J_rX4c0zlnvY6Q',
    appId: '1:716695237276:android:2f2341417cc81ac9523359',
    messagingSenderId: '716695237276',
    projectId: 'fruit-hub-954fa',
    storageBucket: 'fruit-hub-954fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpmyljR8nWo9yvhcT0nr1YZUOeJDWPNKI',
    appId: '1:716695237276:ios:a71d6f18e964adce523359',
    messagingSenderId: '716695237276',
    projectId: 'fruit-hub-954fa',
    storageBucket: 'fruit-hub-954fa.appspot.com',
    androidClientId: '716695237276-3gj9r9pvhhnepr7cj69aap3kjcb6rgco.apps.googleusercontent.com',
    iosClientId: '716695237276-2q67qj6o7fj4rhdmvf13c0o7o9rchtb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpmyljR8nWo9yvhcT0nr1YZUOeJDWPNKI',
    appId: '1:716695237276:ios:a71d6f18e964adce523359',
    messagingSenderId: '716695237276',
    projectId: 'fruit-hub-954fa',
    storageBucket: 'fruit-hub-954fa.appspot.com',
    androidClientId: '716695237276-3gj9r9pvhhnepr7cj69aap3kjcb6rgco.apps.googleusercontent.com',
    iosClientId: '716695237276-2q67qj6o7fj4rhdmvf13c0o7o9rchtb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc_PewOq8vJps7Uo2YhWnpRldg62JVs7U',
    appId: '1:716695237276:web:cef78a14a61e598e523359',
    messagingSenderId: '716695237276',
    projectId: 'fruit-hub-954fa',
    authDomain: 'fruit-hub-954fa.firebaseapp.com',
    storageBucket: 'fruit-hub-954fa.appspot.com',
    measurementId: 'G-JE193NXRX0',
  );
}
